const KINOAFISHA_LOAD = 'kinoafisha_load';
const SET_KINO_AFISHA = 'SET_KINO_AFISHA';
const CLEAR_KINO_AFISHA = 'CLEAR_KINO_AFISHA';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const SIGN_UP = 'SIGN_UP';
const AFISHA_COOKIE_NAME = 'AFISHA_COOKIE_NAME';
const SWITCH_LOADER = 'SWITCH_LOADER';
const SET_FILM = 'SET_FILM'

export { CLEAR_KINO_AFISHA, KINOAFISHA_LOAD, SET_KINO_AFISHA, SIGN_OUT, SIGN_IN, SIGN_UP, AFISHA_COOKIE_NAME, SWITCH_LOADER, SET_FILM };
